name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Run Action
      # You may pin to the exact commit or the version.
      # uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185
      uses: addnab/docker-run-action@v3
      with:
        # Image
        image: damtech123/custom-os-x86_64-environment:latest
        options: -v ${{ github.workspace }}:/work
        run: |
          cd /work/OS
          make all
          make build-x86_64
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          LICENSE.txt
          OS/dist/x86_64/kernel.iso
